name: Deploy Flask App to AKS

on:
  push:
    branches:
      - main
      - develop  # Adiciona a branch `develop` para criar PR automaticamente

env:
  REGISTRY: acrchatgptlab.azurecr.io
  RESOURCE_GROUP: rg-labchatgpt
  AKS_CLUSTER: aks-labchatgpt
  IMAGE_NAME: flask-aks-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        run: az acr login --name acrchatgptlab

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest ./app

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Update AKS Deployment with new image
        run: |
          kubectl set image deployment/flask-aks-app flask-aks-app=$REGISTRY/$IMAGE_NAME:latest --record

  create-pr:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'  # Executa apenas para a branch `develop`
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Atualizando a branch main com a última versão da develop"
          title: "Merge `develop` into `main`"
          body: "Este PR contém as últimas alterações feitas na branch develop."
          base: main  # A branch destino (main)
          branch: develop  # A branch origem (develop)
